apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: owncloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/homelab/apps/owncloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
