apiVersion: v1
kind: Secret
metadata:
  name: owncloud-secret
  namespace: owncloud
type: Opaque
stringData:
  password: "ChangeMe123!"  # Change this to a secure password
---
apiVersion: v1
kind: Secret
metadata:
  name: owncloud-mariadb-secret
  namespace: owncloud
type: Opaque
stringData:
  password: "ChangeMe123!"  # Change this to a secure password
