apiVersion: v1
kind: Namespace
metadata:
  name: egress-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy
  namespace: egress-system
  labels:
    app: squid-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid-proxy
  template:
    metadata:
      labels:
        app: squid-proxy
    spec:
      containers:
      - name: squid
        image: ubuntu/squid:latest
        ports:
        - containerPort: 3128
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: squid-config
          mountPath: /etc/squid/conf.d/
      volumes:
      - name: squid-config
        configMap:
          name: squid-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
  namespace: egress-system
data:
  squid.conf: |
    # Allow GitHub, Docker Hub, and other common services
    acl allowed_http_sites dstdomain .github.com .githubusercontent.com .docker.com .docker.io .quay.io
    acl allowed_https_sites dstdomain .github.com .githubusercontent.com .docker.com .docker.io .quay.io
    acl allowed_ports port 80 443

    # Basic security settings
    http_access allow localhost
    http_access allow allowed_http_sites
    http_access allow allowed_https_sites
    http_access deny all

    # Define listening port
    http_port 3128

    # Logging
    access_log daemon:/var/log/squid/access.log squid
    cache_log /var/log/squid/cache.log
    cache_store_log none

    # Performance tuning
    maximum_object_size 1024 MB
    cache_mem 256 MB
---
apiVersion: v1
kind: Service
metadata:
  name: squid-proxy
  namespace: egress-system
spec:
  selector:
    app: squid-proxy
  ports:
  - name: proxy
    port: 3128
    targetPort: 3128
  type: ClusterIP
