apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-exit-node
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-exit-node
  template:
    metadata:
      labels:
        app: tailscale-exit-node
    spec:
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
        - name: TS_USERSPACE
          value: "true"
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: auth_key
        - name: TS_EXTRA_ARGS
          value: "--advertise-exit-node"
        volumeMounts:
        - name: tailscale-data
          mountPath: /var/lib/tailscale
      volumes:
      - name: tailscale-data
        persistentVolumeClaim:
          claimName: tailscale-data
---
apiVersion: v1
kind: Service
metadata:
  name: tailscale-exit-node
  namespace: tailscale
spec:
  selector:
    app: tailscale-exit-node
  ports:
  - port: 41641
    protocol: UDP
    name: tailscale
