apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: databases
type: Opaque
data:
  # This is a placeholder password. In a production environment, you should use a properly secured secret
  # Base64 encoded value of 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM=
