apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    image:
      repository: n8nio/n8n
      tag: latest
    
    # Database configuration
    # Disable built-in PostgreSQL
    config:
      database:
        type: postgresdb
        postgresdb:
          host: postgres.postgres.svc.cluster.local
          port: 5432
          database: n8n
          user: postgres
          password:
            valueFrom:
              secretKeyRef:
                name: n8n-db-auth
                key: DB_POSTGRESDB_PASSWORD
    
    # Storage configuration - disable persistence
    volumes: []
    volumeMounts: []
    
    # Ingress configuration
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: Prefix
    
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5678"
    
    extraEnv:
      - name: N8N_METRICS
        value: "true"
      - name: N8N_METRICS_PREFIX
        value: "n8n_"
