apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    image:
      repository: n8nio/n8n
      tag: latest
    
    # Database configuration - using external PostgreSQL
    postgresql:
      enabled: false
    
    externalDatabase:
      host: postgres.postgres.svc.cluster.local
      port: 5432
      user: postgres
      database: n8n
      existingSecret: n8n-db-auth
      existingSecretPasswordKey: DB_POSTGRESDB_PASSWORD
    
    # These values are adapted for the community chart
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: Prefix
    
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5678"
    
    n8n:
      metrics:
        enabled: true
        prefix: "n8n_"
    
    # Disable persistence to avoid PVC binding issues
    persistence:
      enabled: false
