apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: ">=0.9.0"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: n8nio/n8n
      tag: latest  # Will be updated by Flux image automation
    
    persistence:
      enabled: true
      size: 10Gi
    
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true  # Prometheus integration
