apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: clusters/homelab/charts/n8n
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: n8nio/n8n
      tag: latest
    # Database configuration
    postgresql:
      enabled: false
      externalDatabase:
        host: postgres.postgres.svc.cluster.local
        port: 5432
        user: postgres
        database: n8n
        existingSecret: n8n-db-auth
        existingSecretPasswordKey: DB_POSTGRESDB_PASSWORD
    
    # Disable Prometheus integration as the CRDs are not installed
    prometheus:
      enabled: false
      serviceMonitor:
        enabled: false
    
    # These values should match our local chart schema
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: Prefix
    
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5678"
    
    env:
      N8N_PORT: 5678
      NODE_ENV: production
      N8N_METRICS: "true"
      N8N_METRICS_PREFIX: "n8n_"
    
    persistence:
      enabled: true
      size: 10Gi
