apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      path: ./clusters/homelab/charts/n8n
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: n8nio/n8n
      tag: latest
    
    persistence:
      enabled: true
      size: 10Gi
    
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: Prefix
    
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
    
    # Database configuration
    postgresql:
      enabled: false
      externalDatabase:
        host: postgres.postgres.svc.cluster.local
        port: 5432
        user: postgres
        database: n8n
        existingSecret: n8n-db-auth
        existingSecretPasswordKey: DB_POSTGRESDB_PASSWORD
