apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "0.9.0"  # Specify exact version for stability
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: n8nio/n8n
      tag: latest  # Will be updated by Flux image automation
    
    persistence:
      enabled: true
      size: 10Gi
    
    ingress:
      enabled: true
      className: nginx  # Updated from annotations
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: Prefix
    
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true  # Prometheus integration
    
    # Database configuration
    postgresql:
      enabled: false  # We're using external PostgreSQL
    
    env:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres.postgres.svc.cluster.local
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: n8n
