apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: n8n
      interval: 1m
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
    cleanupOnFail: true
  values:
    # Image configuration
    image:
      repository: n8nio/n8n
      tag: latest
    
    # Database configuration - using PostgreSQL
    postgresql:
      enabled: false
      externalDatabase:
        host: postgres.postgres.svc.cluster.local
        port: 5432
        user: postgres
        database: n8n
        existingSecret: n8n-db-auth
        existingSecretPasswordKey: DB_POSTGRESDB_PASSWORD
    
    # Optimized for ARM64 low-power hardware
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    
    # Ingress configuration
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: Prefix
    
    # Pod annotations for monitoring
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5678"
    
    # Environment variables for n8n
    env:
      N8N_PORT: 5678
      NODE_ENV: production
      
    # Disable persistence initially to avoid PVC binding issues
    persistence:
      enabled: false
