apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: clusters/homelab/charts/n8n
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: n8nio/n8n
      tag: latest
    
    # Database configuration
    postgresql:
      enabled: false
    
    # These values should match our local chart schema
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: Prefix
    
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5678"
    
    env:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres.postgres.svc.cluster.local
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: n8n-db-auth
            key: DB_POSTGRESDB_PASSWORD
      N8N_METRICS: "true"
      N8N_METRICS_PREFIX: "n8n_"
    
    persistence:
      enabled: true
      size: 10Gi
