apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-postgresql
  namespace: n8n
  labels:
    app: n8n-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-postgresql
  template:
    metadata:
      labels:
        app: n8n-postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: "n8n"
        - name: POSTGRES_PASSWORD
          value: "asunan8n"
        - name: POSTGRES_DB
          value: "n8n"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-postgresql
  namespace: n8n
  labels:
    app: n8n-postgresql
spec:
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    app: n8n-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
