apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-postgresql
  namespace: n8n
  labels:
    app: n8n-postgresql
spec:
  serviceName: n8n-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: n8n-postgresql
  template:
    metadata:
      labels:
        app: n8n-postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: "n8n"
        - name: POSTGRES_PASSWORD
          value: "asunan8n"
        - name: POSTGRES_DB
          value: "n8n"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - n8n
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - n8n
          initialDelaySeconds: 30
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-postgresql
  namespace: n8n
  labels:
    app: n8n-postgresql
spec:
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    app: n8n-postgresql
