apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/infrastructure/cert-manager
  prune: true
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
