apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: homelab
  labels:
    app: n8n
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: automation
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - n8n.fa.pesulabs.net
      secretName: n8n-tls-cert
  rules:
    - host: n8n.fa.pesulabs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 80
