apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: home-assistant-rewrite
  namespace: home-assistant
spec:
  stripPrefix:
    prefixes:
      - /home-assistant
    forceSlash: true
