apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  # Default credentials - you should change these after initial setup
  # admin@example.com / password
  N8N_ENCRYPTION_KEY: "YmFzZTY0ZW5jb2RlZHN0cmluZwo="  # Change this to a secure value
  N8N_BASIC_AUTH_USER: "YWRtaW4="  # admin
  N8N_BASIC_AUTH_PASSWORD: "cGFzc3dvcmQ="  # password
