apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system # Match the namespace in kustomization.yaml
spec:
  interval: 15m
  chart:
    spec:
      # Use direct chart URL instead of HelmRepository sourceRef
      chart: https://charts.bitnami.com/bitnami/sealed-secrets-2.5.7.tgz
      # Version is implicit in the URL
      # sourceRef removed
      interval: 15m # Interval to check the chart URL (can be longer)
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Add any specific values you need here, otherwise defaults are used.
    # For example, if you need specific node selectors or tolerations.
    fullnameOverride: sealed-secrets-controller # Keep the standard controller name
