apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system # Match the namespace in kustomization.yaml
spec:
  interval: 15m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.15.0" # Use a recent version
      sourceRef:
        kind: HelmRepository
        name: bitnami # Assumes bitnami repo is defined in flux-system/sources
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Add any specific values you need here, otherwise defaults are used.
    # For example, if you need specific node selectors or tolerations.
    fullnameOverride: sealed-secrets-controller # Keep the standard controller name
