apiVersion: v1
kind: Service
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    app: authentik-postgresql
  type: ClusterIP
