apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: fa-platform
  labels:
    app.kubernetes.io/name: family-assistant
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: family-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - app.fa.pesulabs.net
      secretName: family-assistant-app-tls
  rules:
    - host: app.fa.pesulabs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
