apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.7.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      kind: DaemonSet
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      extraArgs:
        update-status: "true"
        update-status-on-shutdown: "true"
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
