---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: databases
spec:
  encryptedData:
    password: AgAC3iFZ1JjafcvohvEYGhj3xFs9Fh8YDtSlM9kGItcOyTBVISqrGGGxw6ydf0xFMpo6wHc2K4A7q6hPHOiniuohrEEEnNeCkOTfaSTpT5ct+oIWwGoSet1Zhu0fGhBEgbxzj5m2f4wKTy10y/igti29ODThVegsjHexgjQXv69HXVe8e9R7lq54mrFjaXtMWM5Q3YRGc4QrxOS16SLVnc/zWDiLZDyc+SPT8aKOw/zuOktfzZkXFSS4vov3HqiyOdUHVqa0iWwVIdZtLbP9wz75Z391WeBAksVdIYE6tOb67ZDm8o2AGF+BOpXYk0tq+WBj3lk/qkHINlV9kcY8aRwnm9faUWwPfwMGhpjRjDL+7F1L/YNYuJrDXjo6NW97sbz7nTGke4DWoDZwA3y93+OXOsZwWjYViFXnGM/3BG5x/2RXxHy5HUfwcYigZ3dIJt3h7O/8ZlDysfFHEJZcNONrIpFpbkxpVasnwJ7RBDolHcLqNgwGjJ/dzsserGoZM84M7QG3WSFl1Dh83HtB/zVGVf0c3Vj/a9G1xNuAlntLf8PoWlwFlrTjMon9do62sDWKkp9wqBR3Y6TJPmkIfSrPa8nKXXyDPdP8vXqRU6FWxEPdXDP+AqAdRBP9wB2rEa7qSVQtcmxGfFGcag7JG64cMt1NWN7MKSQCsZaxHGgmzUkurjs4d5ULi+63/CahJDBoocGVMvPcTFY1NaxFQpLG
    username: AgA2dgXmXAp17Bs3RSGozr/qUQPk5PyOV6h/AbsrhWUXxuSiDa7XdKydLRlR2jDtnGM6lXGVuD/pl7IwGtgV/I1Qk3rGPDPcdBGvmrvYJRgv7mh+tMBgtvL4uynZdtigK3q05Kq5AOstQWTxgnKGeRTG360j9goQJJZhH0ZfdbffxRWY+NWomIh44Tvx+CcrWaSFgp789dKjp70yMW6+BzU/z+2kZDXF9RJCSmZdZKPenmoXH6EzfesHawSQdqtr1ck6D1JURNzM20JnFZW7vqaDd76ROffGBwf8TZuJfNMt8mKYb+kGYV4pgeOBz6J7pJ2IyapclNMgLCKeXRdsxli233D9bmTBh7Z06QWsvzuuF1OpMk27BQVqVllgy9UT4ybPqxtNmZ4bdSjOF6d2LkuaJxI1TnVYaKpEd/Aqwd8kbbAg4Xe7MTMYutnkg/Lr3+4iRK4DOp4hqWvXWhxuq/0zGvUsIy+mZabbPZQFkrNjle40cO2G5PBuis0UYCfXKh/+ISwqEZLoUNSBY+ed24dHk8jQX1sH0dtKOECmRyzXwDnk4z6ark90lVbdja+9BegUoPHT+Pm3zkQlA4U29lN1mMZ6WLi70XeaFq2UDjgRWHRA+gYWa3lu8FNFTu5VUbE5Ut3g9JUD2lLemD/G4SMhaTlz8ome9BxNK1OYSTxZh8fXzdYUiapaAzNP0j+qGwIp0Y9XTUfQ0Q==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: databases
    type: Opaque
