---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: databases
spec:
  encryptedData:
    password: AgCXojXoBw0QYMSMNKHPjCeN+M4ZV/C/kjl3dmHQZSajlJlj/0w6VEDh9ng8ygOlkslsCLkZt8FRi1mlGD7XzHMXziHXjspjyt8cjIsDh6anaUCyTvMsxAXhRRWH1S0NQdk3X6XxBRTy+UtVb0iu1gT2SUVjmw37PLgLkS2T/CUNk8Mv3usnVy/0vHaDk1Zhv0peWZrwmyrCqDpJltz9rLkFTVAYRZAboBnksHHBfaf3p8j9+borelSANx4ccxa+sC8vup/UygVMmHDFS8yu6a7krqiorw4DdSaqGN++qRrR82ppcdVk31WAbD6rHM3YYf6tHFYaCz0dwm4BY1rvNMEcUVTkpJnh4v60TlEVngtRKf2Mydag0sgwYoFhzUXGdyudthCFyN89JJhkpC+MfcMOXsRG0asHQY+HV79+vApex3w+bSJDfvnGiC8vw5KAWmUsZ6QXfoDqcTY075CBFZz6P8LEcLP9s3p5X+QJET/jOFzwMD7w43k6mqLti8Ra22MHKgk0kZFe3XV2jVNrO9gMCR8+3SphnO2JxoqzZffdM58+jhKSrHPsflw/q9VS/nD/6ju09rTSnb/JIeBGNjSw+nydn/r3uDfU0nbUfjOcSgV1j4d9senIOEORfrd9d2u06LiNni3JNkRUEfCRaTcsmlPmSyLXuwQs2HnmzY3LEoVZEGfclQH2l8JOg942Bmp5sGhY1RbmoRK+jk11siWM
    username: AgCfhiaRfFVHiYMNLloLKaDqSsGP0SxLUz2kQMeFg+Hf7KRb3oJJLKRtP+aVxiPfh+hsD2wAIjyeu9btGe9kOPvRvkbYFBMrbaYMzmzJYRgAawtJ6v6IObRNGJ+wOP66R5kO1cujngD9HwBYIiDzLXOGkjvzFV4dq/17p+ERqVMelB/U6RD8u71IuaA/WTrLX+1N7TocDTNDcOKQBYdQB2yDjllJKGRrqPzECwfjOh3VcmWZDsXZ3pocQ2Oo15QPhKbD7r/ueN6nJJmyOEpKnHUT+/5Ao3Bv6WJkpGvg+ViKr+srF/Sncp0qKAYaIcr8NmFNDxTp0gBgm+SzI+vpegMZx3rNKw54lK0drEy7ZiqiEf1Uw86uFPzGxN9peVg9ru74Q8dX2rN5GGGpcGXJtofFZsnIehoVbPuYmSOMHqNaBPpTCd8IgbIvAOjXi0PzuzrY0jmvibXWJM01vil6TLYJ3+Neu92dIoT9dnq4ulUzyEmXszI38YXGjIjPHNq0M67KuHEo9xznZZqXUZdq7aoIBPIs2dAxoVmH3iLLCZ2cSRYey0PLTDm5t5gZHj8cZ5CEum7MfLxrrwe+UODdvlz45yEsR4twGdYvlKXeC4lL0lFxsr5Yb/gCX3Xa5luTYTScFFq0pAiyKVIL/6kMKtmvG/ZmjQjdeUinFSll6AF6XdYXpaIzt/mChY8cuPMVuzqO8AWvCtsQSg==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: databases
    type: Opaque
