apiVersion: v1
kind: Service
metadata:
  name: authentik-redis
  namespace: authentik
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: authentik-redis
  type: ClusterIP
