apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
data:
  # This is a placeholder - you'll need to replace with your actual base64-encoded Tailscale auth key
  # Generate a new key at https://login.tailscale.com/admin/settings/keys without tags
  # Then base64 encode it with: echo -n "tskey-auth-YOUR-ACTUAL-KEY" | base64
  auth_key: dHNrZXktYXV0aC1LRVktRVhBTVBMRS1QTEFDRUhPTERFUg==
