apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: tailscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: tailscale
  labels:
    app: coredns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      serviceAccountName: coredns
      containers:
      - name: coredns
        image: coredns/coredns:1.10.1
        args: ["-conf", "/etc/coredns/Corefile"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
      volumes:
      - name: config-volume
        configMap:
          name: coredns
          items:
          - key: Corefile
            path: Corefile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: tailscale
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
    }

    app.pesulabs.net:53 {
        errors
        hosts {
            10.43.56.28 grafana.app.pesulabs.net
            10.43.184.103 prometheus.app.pesulabs.net
            10.43.81.86 loki.app.pesulabs.net
            fallthrough
        }
        cache 30
    }
    
    db.pesulabs.net:53 {
        errors
        hosts {
            10.43.186.130 postgres.db.pesulabs.net
            10.43.210.80 qdrant.db.pesulabs.net
            fallthrough
        }
        cache 30
    }
  pesulabs.conf: |
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: tailscale
  labels:
    app: coredns
spec:
  selector:
    app: coredns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
