apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-config
  namespace: tailscale
data:
  run.sh: |
    #!/bin/sh
    set -e
    
    tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
    
    # Give tailscaled some time to start up
    sleep 5
    
    # Reset configuration and apply new settings
    tailscale up \
      --reset \
      --authkey="${TS_AUTHKEY}" \
      --hostname="${TS_HOSTNAME}" \
      --advertise-routes="${TS_ROUTES}" \
      --advertise-exit-node \
      --accept-dns=true
      
    # Keep the container running
    exec tail -f /dev/null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      containers:
      - name: tailscale
        imagePullPolicy: Always
        image: tailscale/tailscale:stable
        command: ["/bin/sh", "/scripts/run.sh"]
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: auth_key
        - name: TS_ROUTES
          value: "10.0.0.0/8"
        - name: TS_HOSTNAME
          value: "k8s-homelab-router"
        volumeMounts:
        - name: tailscale-data
          mountPath: /var/lib/tailscale
        - name: scripts
          mountPath: /scripts
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      volumes:
      - name: tailscale-data
        emptyDir: {}
      - name: scripts
        configMap:
          name: tailscale-config
          defaultMode: 0755
      serviceAccountName: proxies
