apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
  namespace: tailscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
spec:
  serviceName: "tailscale-subnet-router"
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      containers:
      - name: tailscale
        imagePullPolicy: Always
        image: tailscale/tailscale:stable
        env:
        - name: TS_STATE_DIR
          value: "/var/lib/tailscale"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: auth_key
        - name: TS_USERSPACE
          value: "true"
        - name: TS_ROUTES
          value: "10.0.0.0/8"
        - name: TS_HOSTNAME
          value: "k8s-homelab-router"
        - name: TS_EXTRA_ARGS
          value: "--advertise-routes=10.0.0.0/8 --advertise-exit-node --advertise-tags=tag:infra --accept-dns=true"
        - name: TS_TAILSCALED_EXTRA_ARGS
          value: "--tun=userspace-networking --socks5-server=localhost:1055"
        volumeMounts:
        - name: tailscale-state
          mountPath: /var/lib/tailscale
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      volumes:
      - name: tailscale-state
        persistentVolumeClaim:
          claimName: tailscale-state
      serviceAccountName: proxies
