apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-config
  namespace: tailscale
data:
  run.sh: |
    #!/bin/sh
    set -e

    # Start tailscaled in userspace mode as required in the memory
    echo "Starting tailscaled in userspace mode..."
    tailscaled --tun=userspace-networking &
    
    # Wait for tailscaled to start
    sleep 5
    
    # Authenticate and enable subnet routing for 10.0.0.0/8
    echo "Authenticating to Tailscale and advertising subnet ${TS_ROUTES}..."
    tailscale up \
      --authkey="${TS_AUTHKEY}" \
      --hostname="${TS_HOSTNAME}" \
      --advertise-routes="${TS_ROUTES}" \
      --accept-dns=false
    
    # Display status
    echo "Tailscale status:"
    tailscale status
    
    # Important reminder for the user
    echo "NOTE: Routes need to be approved in the Tailscale admin console"
    echo "Please visit https://login.tailscale.com/admin/machines"
    
    # Keep container running
    exec tail -f /dev/null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "/scripts/run.sh"]
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: auth_key
        - name: TS_ROUTES
          value: "10.0.0.0/8"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_HOSTNAME
          value: "k8s-homelab-router"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - name: tailscale-data
          mountPath: /var/lib/tailscale
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: tailscale-data
        emptyDir: {}
      - name: scripts
        configMap:
          name: tailscale-config
          defaultMode: 0755
