apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
data:
  # This contains the Tailscale auth key encoded in base64
  auth_key: dHNrZXktYXV0aC1rSjRSeFJjZGRhMTFDTlRSTC15VEFDalljdHhaTTlVaVNBNXVmWFpNTUZicjF0dzdWbzk=