---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAQ2DmF7d4/wgFR3JM0Dc9Ek6hgYz4apl6ATrQsrl5qS52BmMx4Frx956Dk3ucUR67T6PjMM8L7Jm9Ph38m8tP/jGTAGw8AzHT2Jzk3IEiU91MbIz9BD0D62YHur7BzzWh91zAfPj6hsReV2Xc4MqoCGiq/6S1LhkhF8bILVfnE8cFCicok58qQkFQo5QtLphPbIvIritxB56xRQieWo8VYnIj4vzxdUKYX1N0GPpEKsIwkzTv6bD+4o7VvY/tCcLWea3o3jZrS4BQOmgh1vIrmC7YLKc7bQlqBzLtUebfXYeB8uH8GbwbRQwMTpYzJ60Q26psXiWELPxtUMhX0EzpAgow385TQc7zmnZGVHc/X5nsJe7ORk9nDA5vz//SOFY++kunHEGqKFRc8EbWnCBgz+HH0Rb+jGuIwH1GmICgwArKwe6MaP2Git9c9tBxI1F7XqNf1ZFyxvJNBPoBpZBMt94oflHawvSDdrsFzjuTL3sIaE36EVEURoxQYmqPdFurmuFZC5P11KpYNRYC13VHn6MzLMoLzJIdBB/JOlwsZMt4zL+QbtdXX8NEj7YR4rbJPvAX9ZAEy0JADG6by6MeR8qnl7OqjRb7QlMyiSdwY/NNRzG24QuO8leJ8M5fuqc40sg/WgtOAtO+Zc8vrA2j/xsjFxe+/qxlJI5Xr4tsNZ6b2iZvQMrYojwL6DzdhwRBE3S1gBwqiZxjJ1fqFgmLR/w==
    client_secret: AgCzDjZsLfT9MwtaWREZsFvvthNu9hB03whSxWpnFHp0tXSmJxVFvymwPVulLAAmpu2lW/5M2PdH0Ig/Ky1osOqg+0y168Ep4hTsUBGtGn+b75bO6Jndrr+S3VwqRUSQvitYP1EQlm/3aRdGEmKaZPehTIciGJBwIXvva8rdLtl6Fpxvx5CuEDpzMeHUuzcM1hcNofl05rCwwa5btTnmEXC8GiOJPlJbpJ2TxrNOmwKobdyWgh9mGQQGHnMTODlWxouplbX74BeJaoGyoo6meAMhM15qYPmsM2cO4AcVrZdztR/jXqDr8aoTRT4JRrr8fJQzNWeeRs36hRvVRLtvHAn+r5Ss1qB3KSrkkWR676KCES99q58x8zXJbgg9wjhPFmrPnu+eY5YoFrJUssgHS/PBqnEVVYBRpz7fAhJWgx4GuLREZbVDqRJ3qBUGPWuj/hiVR3JneVBqtudEs/ulTTyREd/uHXE26m8kU/1xFYP6iUvScIgVMs/HIRSLp8ub4fNsQWjsKe9qcg7SyhUGyOS/oPzkHuWHLpyhstjuEu4ugb/X1R0T4fVczuRKretgNmhsTximS8Lk6SJRD4l4+R4/FyFrbvYh89+Ahl3lbyHkby4vMv0f2nRszM/vw/KZh19pwxN9czbfBWwztCU5jI/u6ntZiXY887LtaXyWuMB3/O4xCMNSr3cCWtrMdovx0q+ZRmZpEk2QnIwBUGvm7jufvMuhoiAPJJgX2f/I8sdndgnP2rqwREPwGYkIfFb4/RNHf0TLfIxjKThVVbzg/uE=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
