apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.8.11"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  values:
    # Single binary mode for smallest footprint
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      # Optimized for ARM64 low-power hardware
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    # Disable components not needed for small deployments
    gateway:
      enabled: false
    # Single instance mode for resources
    singleBinary:
      replicas: 1
    # Persistence for logs
    persistence:
      enabled: true
      size: 5Gi
    # Promtail for log collection
    promtail:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
