apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  homelab.server: |
    homelab.local {
        hosts {
            192.168.86.200 grafana.homelab.local
            192.168.86.200 prometheus.homelab.local
            192.168.86.200 loki.homelab.local
            192.168.86.200 postgres.homelab.local
            192.168.86.200 qdrant.homelab.local 
            192.168.86.200 homer.homelab.local
            fallthrough
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        import /etc/coredns/homelab.server
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
