apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-hosts-fix-complete
  namespace: kube-system
data:
  hosts-patch.sh: |
    #!/bin/sh
    # Add registry hostnames to the host node's /etc/hosts
    cat <<EOF >> /etc/hosts
    # Container registry hostnames - added to fix DNS resolution issues
    44.208.254.194 registry-1.docker.io
    3.94.224.37 registry-1.docker.io
    98.85.153.80 registry-1.docker.io
    
    # Docker Hub authentication service
    3.216.34.172 auth.docker.io
    34.205.13.154 auth.docker.io
    
    # Common registries
    140.82.121.33 ghcr.io
    140.82.121.34 ghcr.io
    185.199.108.133 raw.githubusercontent.com
    185.199.109.133 raw.githubusercontent.com
    185.199.110.133 raw.githubusercontent.com
    EOF
    
    # Ensure DNS resolution is working by updating resolv.conf
    cat <<EOF > /etc/resolv.conf
    nameserver 8.8.8.8
    nameserver 1.1.1.1
    EOF
    
    # Restart containerd to apply the changes
    systemctl restart containerd
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fix-registry-dns-complete
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      hostNetwork: true
      hostPID: true
      restartPolicy: Never
      containers:
      - name: host-modifier
        image: ghcr.io/home-assistant/home-assistant:2025.3.3
        command: ["bash", "-c"]
        args:
        - |
          cp /scripts/hosts-patch.sh /host-root/tmp/
          nsenter -t 1 -m -u -n -i sh /tmp/hosts-patch.sh
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host-root
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: scripts
        configMap:
          name: registry-hosts-fix-complete
          defaultMode: 0755
