apiVersion: v1
kind: Service
metadata:
  name: cluster-dns-sharing
  namespace: tailscale
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "k8s-dns"
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  type: ClusterIP
