apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
  namespace: tailscale
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # Use the default StorageClass
  resources:
    requests:
      storage: 1Gi # Or adjust size as needed
