---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale
  namespace: tailscale
spec:
  encryptedData:
    key: AgBAnH99ndt5buigmAL4hYA9Hg0D1638aVXtv+WGb6BXPbfVjwLofLgwkVIsEQN/tD9akQXV5Zx0mKj5p7wXfQTZrhIykaMbHntdBjIBzan8iwYJXEgDXoywUqNukSDcr1aaRO640c+Mfai3kh62iyhCemWs0HtDEtzzU08pSE5ON8QOFNpjW/YtCWhVbR7K7cqoUweqyugUMNMTyxMlIWLjf64AjL0BoyysoMwaveqG+wKCR0I3D2Q82Zds7Or2sgqNGOImAudN84/fAYYFkiMMgm9Wx7U0AmrKtZY/2mABKmQntJFjOp37fhPHUpsmP7uy04DH74EgLm/NG7kxoF4rnMEUts7oDj/spKCGdEkoePYtRO8fKXYrtRe663SMDqApZlfV5qJ3iFgOk+Gua7Q0qyAdeAkDlmNGsWpcw0wCL5LMGs/aE+RHYFIzrAKilcV/m+qo/712TpptDmClYqgmJH9/gAw9oApQ1QIUDrfMRCeY1X53CvEDyIhGziIwamR7o2q+dMEKUHwPp6I6nhMDiOZMSmvTOUj4heyTPaFPraHDBhe/I/m4x5C+zZqII/uhpvP/RxJuQTIyw8XKGfGQ8va0vwFCKNamroKkJV2GjJTTArlIaLZMQRPMPQfpB2b4Wmvgyo6T5bhHAEZGfSiVMxVm5V4xlrstxigvCuI7gw4m/fuuKtRKDoYMshhf71KIslK5RZgEBMCKiA8TA9oqJSJg7OoYzMVpa7AxLrlchbxmIWvMEfaIG0XsIv69N28Vv0nhSgrEbnX/3yDUdQ==
  template:
    metadata:
      creationTimestamp: null
      name: tailscale
      namespace: tailscale
    type: Opaque
