apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
stringData:
  # Replace this with your actual Tailscale auth key
  TS_AUTH_KEY: "REPLACE_WITH_YOUR_ACTUAL_AUTH_KEY"
