apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-assistant-backend
  namespace: homelab
  labels:
    app: family-assistant-backend
    component: familyai-v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: family-assistant-backend
      component: familyai-v3
  template:
    metadata:
      labels:
        app: family-assistant-backend
        component: familyai-v3
    spec:
      containers:
      - name: family-assistant
        image: family-assistant:fixed
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
          name: http-api
        - containerPort: 8123
          name: ha-api
        - containerPort: 8008
          name: matrix-api
        env:
        - name: DATABASE_URL
          value: "postgresql://homelab:your_password_here@postgres.homelab.svc.cluster.local:5432/homelab"
        - name: REDIS_URL
          value: "redis://redis.homelab.svc.cluster.local:6379"
        - name: PYTHONPATH
          value: "/app:/app/api:/app/config:/app/agents:/app/services:/app/models"
        - name: QDRANT_URL
          value: "http://qdrant.homelab.svc.cluster.local:6333"
        - name: QDRANT_GRPC_URL
          value: "http://qdrant.homelab.svc.cluster.local:6334"
        - name: OLLAMA_URL
          value: "http://ollama.ollama.svc.cluster.local:11434"
        - name: MEM0_URL
          value: "http://mem0.homelab.svc.cluster.local:30880"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: family-assistant-backend
  namespace: homelab
  labels:
    app: family-assistant-backend
    component: familyai-v3
spec:
  selector:
    app: family-assistant-backend
    component: familyai-v3
  ports:
  - name: http-api
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: ha-api
    port: 8123
    targetPort: 8123
    protocol: TCP
  - name: matrix-api
    port: 8008
    targetPort: 8008
    protocol: TCP
  type: ClusterIP