# Family Assistant Enhancement - Add-on Services
# This adds new capabilities to the existing Family Assistant without disrupting it

apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-assistant-enhancement
  namespace: homelab
  labels:
    app: family-assistant-enhancement
    component: familyai-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: family-assistant-enhancement
  template:
    metadata:
      labels:
        app: family-assistant-enhancement
        component: familyai-v3
    spec:
      containers:
      # Home Assistant Integration Sidecar
      - name: home-assistant-integration
        image: nginx:alpine  # Placeholder - would be familyai-platform:latest
        command: ["python", "-m", "services.home_assistant_integration"]
        ports:
        - containerPort: 8123
          name: ha-api
        env:
        - name: HOME_ASSISTANT_URL
          value: "http://homeassistant.local:8123"
        - name: DATABASE_URL
          value: "postgresql://homelab:$(POSTGRES_PASSWORD)@postgres.homelab.svc.cluster.local:5432/homelab"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
              optional: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8123
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8123
          initialDelaySeconds: 5
          periodSeconds: 5

      # Matrix Integration Sidecar
      - name: matrix-integration
        image: nginx:alpine  # Placeholder - would be familyai-platform:latest
        command: ["python", "-m", "services.matrix_service"]
        ports:
        - containerPort: 8008
          name: matrix-api
        env:
        - name: MATRIX_HOMESERVER
          value: "https://matrix.org"
        - name: DATABASE_URL
          value: "postgresql://homelab:$(POSTGRES_PASSWORD)@postgres.homelab.svc.cluster.local:5432/homelab"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
              optional: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: family-assistant-enhancement
  namespace: homelab
  labels:
    app: family-assistant-enhancement
    component: familyai-v3
spec:
  selector:
    app: family-assistant-enhancement
  ports:
  - name: ha-api
    port: 8123
    targetPort: 8123
    protocol: TCP
  - name: matrix-api
    port: 8008
    targetPort: 8008
    protocol: TCP
  type: ClusterIP

---
# Enhanced Ingress that adds new routes to existing Family Assistant
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: family-assistant-enhanced-ingress
  namespace: homelab
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
    # Add middleware for enhanced features
    traefik.ingress.kubernetes.io/router.middlewares: "familyai-ratelimit@kubernetescrd"
  labels:
    app: family-assistant-enhancement
    component: familyai-v3
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - family-assistant.homelab.pesulabs.net
    - home-assistant.family-assistant.homelab.pesulabs.net
    - matrix.family-assistant.homelab.pesulabs.net
    secretName: family-assistant-enhanced-tls
  rules:
  # Enhanced Family Assistant routes (existing + new v3 endpoints)
  - host: family-assistant.homelab.pesulabs.net
    http:
      paths:
      - path: /api/v3
        pathType: Prefix
        backend:
          service:
            name: family-assistant-enhancement
            port:
              number: 8123  # Forward to enhancement service
      - path: /api/v2
        pathType: Prefix
        backend:
          service:
            name: family-assistant-enhancement
            port:
              number: 8123  # Forward to enhancement service
      - path: /
        pathType: Prefix
        backend:
          service:
            name: family-assistant
            port:
              number: 8001  # Keep existing service for backward compatibility

  # Home Assistant Integration
  - host: home-assistant.family-assistant.homelab.pesulabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: family-assistant-enhancement
            port:
              number: 8123

  # Matrix Integration
  - host: matrix.family-assistant.homelab.pesulabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: family-assistant-enhancement
            port:
              number: 8008

---
# Rate Limiting Middleware for Family Assistant
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: familyai-ratelimit
  namespace: homelab
spec:
  rateLimit:
    period: 1m
    average: 100
    burst: 200

---
# Enhanced Family Assistant ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: family-assistant-enhanced-config
  namespace: homelab
  labels:
    app: family-assistant-enhancement
    component: familyai-v3
data:
  # Home Assistant Integration Config
  home-assistant-config.yaml: |
    home_assistant:
      url: "${HOME_ASSISTANT_URL}"
      token: "${HOME_ASSISTANT_TOKEN}"
      webhook_id: "familyai-webhook"
      automations:
        enabled: true
        family_routines:
          - morning_routine
          - bedtime_reminders
          - homework_time
      devices:
        lights: true
        thermostat: true
        security: true
        speakers: true

  # Matrix Integration Config
  matrix-config.yaml: |
    matrix:
      homeserver: "${MATRIX_HOMESERVER}"
      username: "${MATRIX_USERNAME}"
      access_token: "${MATRIX_ACCESS_TOKEN}"
      rooms:
        family_general: "!family_room_id:matrix.org"
        parents_only: "!parents_room_id:matrix.org"
        kids_zone: "!kids_room_id:matrix.org"
      features:
        encryption: true
        voice_messages: true
        file_sharing: true
        reactions: true

  # Enhanced Features Config
  enhanced-features.yaml: |
    bilingual_support:
      enabled: true
      default_language: "es"
      auto_detect: true
      languages: ["es", "en"]
      cultural_context: "family"

    parental_controls:
      enabled: true
      features:
        - content_filtering
        - screen_time_limits
        - access_controls
        - activity_monitoring

    voice_enhanced:
      whisper_model: "small"
      tts_provider: "local"
      languages: ["es", "en"]
      voice_profiles: true

    dashboard_enhanced:
      role_based_widgets: true
      real_time_updates: true
      family_analytics: true
      export_formats: ["pdf", "csv"]

---
# Database Migration Job (to add new tables/enhancements)
apiVersion: batch/v1
kind: Job
metadata:
  name: family-assistant-db-migration
  namespace: homelab
  labels:
    app: family-assistant-enhancement
    component: migration
spec:
  template:
    metadata:
      labels:
        app: family-assistant-enhancement
        component: migration
    spec:
      containers:
      - name: migration
        image: postgres:16-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Running Family Assistant v3 database migration..."
          PGPASSWORD="$POSTGRES_PASSWORD" psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB << 'EOF'

          -- Add family members table if not exists
          CREATE TABLE IF NOT EXISTS family_members (
              id SERIAL PRIMARY KEY,
              name VARCHAR(255) NOT NULL,
              role VARCHAR(50) NOT NULL CHECK (role IN ('parent', 'teenager', 'child', 'grandparent')),
              age INTEGER,
              preferences JSONB DEFAULT '{}',
              parental_controls JSONB DEFAULT '{}',
              language_preference VARCHAR(10) DEFAULT 'es',
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
              updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );

          -- Add home assistant integration table
          CREATE TABLE IF NOT EXISTS home_assistant_devices (
              id SERIAL PRIMARY KEY,
              device_id VARCHAR(255) UNIQUE NOT NULL,
              name VARCHAR(255) NOT NULL,
              device_type VARCHAR(100) NOT NULL,
              capabilities JSONB DEFAULT '{}',
              family_member_id INTEGER REFERENCES family_members(id),
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );

          -- Add matrix integration table
          CREATE TABLE IF NOT EXISTS matrix_rooms (
              id SERIAL PRIMARY KEY,
              room_id VARCHAR(255) UNIQUE NOT NULL,
              name VARCHAR(255) NOT NULL,
              room_type VARCHAR(50) DEFAULT 'general',
              encrypted BOOLEAN DEFAULT true,
              family_members INTEGER[] DEFAULT '{}',
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );

          -- Add voice interactions table
          CREATE TABLE IF NOT EXISTS voice_interactions (
              id SERIAL PRIMARY KEY,
              conversation_id VARCHAR(255),
              family_member_id INTEGER REFERENCES family_members(id),
              original_audio_url TEXT,
              transcription TEXT,
              ai_response TEXT,
              response_audio_url TEXT,
              language VARCHAR(10),
              confidence FLOAT,
              duration_seconds FLOAT,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );

          -- Update existing tables with new columns
          ALTER TABLE conversations ADD COLUMN IF NOT EXISTS family_member_id INTEGER REFERENCES family_members(id);
          ALTER TABLE conversations ADD COLUMN IF NOT EXISTS language VARCHAR(10) DEFAULT 'es';
          ALTER TABLE conversations ADD COLUMN IF NOT EXISTS interaction_type VARCHAR(50) DEFAULT 'text';

          EOF

          echo "Migration completed successfully!"
        env:
        - name: POSTGRES_HOST
          value: "postgres.homelab.svc.cluster.local"
        - name: POSTGRES_USER
          value: "homelab"
        - name: POSTGRES_DB
          value: "homelab"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
              optional: true
      restartPolicy: OnFailure