apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
type: Opaque
stringData:
  api-token: your-cloudflare-api-token-here  # Replace with your Cloudflare API token
