apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "1.13.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    provider: cloudflare
    cloudflare:
      apiToken:
        secretName: cloudflare-api-token
        secretKey: api-token
      proxied: true
    policy: sync
    sources:
      - ingress
    domainFilters:
      - "yourdomain.com"  # replace with your actual domain
    txtOwnerId: "homelab"
    interval: "2m"
    logLevel: debug
