apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-api-proxy
  namespace: immich
  labels:
    app: immich-api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-api-proxy
  template:
    metadata:
      labels:
        app: immich-api-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: immich-api-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-api-proxy-config
  namespace: immich
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        # Redirect old API endpoints to new ones
        location /api/server-info/ping {
            return 307 /api/server/ping;
        }

        location /api/server-info/config {
            return 307 /api/server/config;
        }

        location /api/server-info {
            return 307 /api/server;
        }

        # Pass all other requests to the Immich server
        location / {
            proxy_pass http://immich-server:3001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: immich-api-proxy
  namespace: immich
spec:
  selector:
    app: immich-api-proxy
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
