apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v1.129.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: MACHINE_LEARNING_CACHE_FOLDER
              value: /cache
            - name: MODEL_DIR
              value: /model
            - name: LOG_LEVEL
              value: "info"
            - name: IMMICH_SERVER_URL
              value: "http://immich-server:3001"
            - name: IMMICH_BASE_PATH
              value: "/immich"
          volumeMounts:
            - name: immich-machine-learning
              mountPath: /cache
            - name: immich-machine-learning
              mountPath: /model
      volumes:
        - name: immich-machine-learning
          persistentVolumeClaim:
            claimName: immich-machine-learning
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  selector:
    app: immich-machine-learning
  ports:
    - port: 3003
      targetPort: 3003
