apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservices
  namespace: immich
  labels:
    app: immich-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-microservices
  template:
    metadata:
      labels:
        app: immich-microservices
    spec:
      containers:
        - name: microservices
          image: ghcr.io/immich-app/immich-server:v1.99.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["node dist/microservices/main.js"]
          env:
            - name: IMMICH_MEDIA_LOCATION
              value: /usr/src/app/upload
            - name: IMMICH_CONFIG_FILE
              value: /usr/src/app/config/immich-config.json
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: REDIS_PASSWORD
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: "info"
            - name: IMMICH_SERVER_URL
              value: "https://asuna.chimp-ulmer.ts.net/immich"
            - name: IMMICH_BASE_PATH
              value: "/immich"
            - name: MICROSERVICES_ENABLED
              value: "true"
          volumeMounts:
            - name: immich-library
              mountPath: /usr/src/app/upload
      volumes:
        - name: immich-library
          persistentVolumeClaim:
            claimName: immich-library
