apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-nginx-config
  namespace: immich
data:
  immich-config: |
    # Configuration for Immich Web
    location / {
      proxy_pass http://immich-web:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Configuration for Immich API Server
    location /api {
      proxy_pass http://immich-server:3001;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Increase the proxy timeouts to handle longer requests
    proxy_connect_timeout 90s;
    proxy_send_timeout 90s;
    proxy_read_timeout 90s;
    
    # Support for large uploads
    client_max_body_size 50G;

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: immich-api-redirects
  namespace: immich
spec:
  redirectRegex:
    regex: ^/api/server-info/(.*)
    replacement: /api/server/$1
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: immich-strip-api-prefix
  namespace: immich
spec:
  stripPrefix:
    prefixes:
      - /api
    forceSlash: true
