apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
  labels:
    type: local
spec:
  capacity:
    storage: 100Gi
  storageClassName: immich-library
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/homedrive/immich/library
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-data
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  storageClassName: immich-postgres-data
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/homedrive/immich/postgres-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-redis-data
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: immich-redis-data
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/homedrive/immich/redis-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-machine-learning
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: immich-machine-learning
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/homedrive/immich/machine-learning
