apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
type: Opaque
stringData:
  DB_PASSWORD: "ChangeMe123!"
  DB_USERNAME: "postgres"
  POSTGRES_PASSWORD: "ChangeMe123!"
  POSTGRES_USER: "postgres"
  REDIS_PASSWORD: ""
