apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v1.129.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /usr/src/app
              exec node ./dist/main web
          ports:
            - containerPort: 2283
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: REDIS_PASSWORD
            - name: IMMICH_MEDIA_LOCATION
              value: /usr/src/app/upload
            - name: IMMICH_CONFIG_FILE
              value: /usr/src/app/config/immich-config.json
            - name: IMMICH_REVERSE_GEOCODING_ENABLED
              value: "false"
            - name: IMMICH_SERVER_URL
              value: "https://immich.app.pesulabs.net"
            - name: IMMICH_BASE_PATH
              value: ""
            - name: PUBLIC_IMMICH_SERVER_URL
              value: "https://immich.app.pesulabs.net"
            - name: PUBLIC_BASE_PATH
              value: ""
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: "info"
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
              value: ""
          volumeMounts:
            - name: immich-library
              mountPath: /usr/src/app/upload
            - name: immich-config
              mountPath: /usr/src/app/config
          startupProbe:
            httpGet:
              path: /
              port: 2283
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 2283
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 2283
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
      volumes:
        - name: immich-library
          persistentVolumeClaim:
            claimName: immich-library
        - name: immich-config
          configMap:
            name: immich-config
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
    - port: 2283
      targetPort: 2283
