apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:release
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2283
          env:
            - name: IMMICH_MEDIA_LOCATION
              value: /usr/src/app/upload
            - name: IMMICH_CONFIG_FILE
              value: /usr/src/app/config/immich-config.json
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: REDIS_PASSWORD
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: "info"
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
              value: ""
            - name: IMMICH_REVERSE_GEOCODING_ENABLED
              value: "false"
            - name: IMMICH_SERVER_URL
              value: "https://asuna.chimp-ulmer.ts.net/immich"
            - name: IMMICH_BASE_PATH
              value: "/immich"
          volumeMounts:
            - name: immich-library
              mountPath: /usr/src/app/upload
            - name: immich-config
              mountPath: /usr/src/app/config
          startupProbe:
            httpGet:
              path: /server-info/ping
              port: 2283
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /server-info/ping
              port: 2283
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /server-info/ping
              port: 2283
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
      volumes:
        - name: immich-library
          persistentVolumeClaim:
            claimName: immich-library
        - name: immich-config
          configMap:
            name: immich-config
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
    - port: 3001
      targetPort: 2283
