apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-web
  namespace: immich
  labels:
    app: immich-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-web
  template:
    metadata:
      labels:
        app: immich-web
    spec:
      containers:
        - name: web
          image: ghcr.io/immich-app/immich-web:release
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          env:
            - name: PUBLIC_IMMICH_SERVER_URL
              value: "https://immich.app.pesulabs.net/api"
            - name: IMMICH_SERVER_URL
              value: "http://immich-server:3001"
            - name: PUBLIC_BASE_PATH
              value: ""
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: immich-web
  namespace: immich
spec:
  selector:
    app: immich-web
  ports:
    - port: 3000
      targetPort: 3000
