apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    kustomize.toolkit.fluxcd.io/force: "enabled"  # Force Flux to apply this patch
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: 32737  # Fixed NodePort for HTTP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
      nodePort: 32720  # Fixed NodePort for HTTPS
