apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/8gears/n8n-helm-chart/blob/main/charts/n8n/Chart.yaml
  timeout: 3m
